version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uriel_db
    volumes:
      - uriel_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 -- npx sequelize db:migrate && npm start" 
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      DB_HOST: db
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DATABASE_NAME: 'uriel_db'
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    

volumes:
  uriel_pgdata:

