openapi: 3.0.0
info:
  title: URIEL
  description: Uriel is an Organisational management app, that allows users of an organisation create and manage both projects and people.
  version: 1.0.0
  contact:
    name: Anaele Joshua
    url: https://github.com/AnaeleJoshua
    email: yourname@example.com
servers:
  - url: http://localhost:3000
    description: Development Server
paths:
  /api/v1/auth/register:
    post:
      summary: Register a new user
      requestBody:
        description: User registration data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: Password123
                firstName:
                  type: string
                  example: John
                lastName:
                  type: string
                  example: Doe
                phone:
                  type: string
                  example: "+123456789"
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
  /auth/login:
    post:
      summary: Login a user and get access token
      requestBody:
        description: User login credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: Password123
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
  /auth/refresh:
    post:
      summary: Refresh access token
      responses:
        '200':
          description: Access token refreshed
        '401':
          description: Unauthorized
  /organisations/{id}:
    get:
      summary: Get organisation by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Organisation retrieved successfully
        '404':
          description: Organisation not found
    post:
      summary: Add a user to an organisation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: User ID to add
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  example: 1
      responses:
        '200':
          description: User added to the organisation successfully
        '404':
          description: Organisation or user not found      
  /organisations:
    get:
      summary: Get all organisations for a user
      responses:
        '200':
          description: Organisations retrieved successfully
        '404':
          description: No organisations found
    post:
      summary: Create a new organisation
      requestBody:
        description: Organisation data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: My Organisation
                description:
                  type: string
                  example: A description of the organisation
      responses:
        '201':
          description: Organisation created successfully
        '400':
          description: Invalid input
  
components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: integer
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        refreshToken:
          type: string
    Organisation:
      type: object
      properties:
        orgId:
          type: integer
        name:
          type: string
        description:
          type: string
        createdBy:
          type: string
